# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  target 'Pharmacy' do
      pod 'SQLite.swift', '~> 0.11.4'
  end

  # Pods for Pharmacy

  target 'PharmacyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PharmacyUITests' do
    inherit! :search_paths
    # Pods for testing
  end
